--gtk-version=4

# My flags idk
# --enable-features=AcceleratedVideoDecodeLinuxZeroCopyGL,AcceleratedVideoEncoder,VaapiOnNvidiaGPUs,WaylandLinuxDrmSyncobj

# https://source.chromium.org/chromium/chromium/src/+/main:docs/gpu/vaapi.md

# VaAPI on Linux witch Vulkan
# --use-gl=angle
# --use-angle=vulkan
# --enable-features=AcceleratedVideoEncoder,VaapiOnNvidiaGPUs,VaapiIgnoreDriverChecks,Vulkan,DefaultANGLEVulkan,VulkanFromANGLE
# --ignore-gpu-blocklist
# --disable-gpu-driver-bug-workaround

#VaAPI on Linux with OpenGL
--use-gl=angle
--use-angle=gl
--enable-features=AcceleratedVideoEncoder,AcceleratedVideoDecodeLinuxGL,VaapiOnNvidiaGPUs,AcceleratedVideoDecodeLinuxZeroCopyGL
--ignore-gpu-blocklist
--disable-gpu-driver-bug-workaround
