--gtk-version=4

--ignore-gpu-blocklist
--enable-zero-copy

# --enable-features=AcceleratedVideoDecodeLinuxGL,AcceleratedVideoEncoder,VaapiOnNvidiaGPUs,WaylandLinuxDrmSyncobj
#--enable-features=AcceleratedVideoDecodeLinuxGL,AcceleratedVideoDecodeLinuxZeroCopyGL,AcceleratedVideoEncoder,VaapiOnNvidiaGPUs,WaylandLinuxDrmSyncobj
--enable-features=VaapiVideoDecoder,VaapiIgnoreDriverChecks,Vulkan,DefaultANGLEVulkan,VulkanFromANGLE,WaylandLinuxDrmSyncobj,AcceleratedVideoEncoder

# --disable-features=UseChromeOSDirectVideoDecoder

